import type {
  LegislativeDocument,
  SessionMinutes,
  User,
  AuditLogEntry,
  DocumentRequest,
  Category,
  SBMember,
  Committee,
  CSOOrganization,
  CommitteeReport,
} from "./types";

// Sample PDFs in public/documents/ for view/download (add files to repo or copy from Downloads)
export const SAMPLE_PDF_SNORKELING =
  "/documents/MUN_ORD_02_2017_SNORKELING_ORDINANCE.pdf";
export const SAMPLE_PDF_TRICYCLE =
  "/documents/MUN_ORD_04_2022_TRICYCLE_TARIFF_AMENDMENT_SIGNED.pdf";
export const SAMPLE_PDF_EUF =
  "/documents/MUN_ORD_12_2014_EUF_AMENDMENT.pdf";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Environment", isActive: true },
  { id: "cat-2", name: "Infrastructure", isActive: true },
  { id: "cat-3", name: "Taxes", isActive: true },
  { id: "cat-4", name: "Fees and Charges", isActive: true },
  { id: "cat-5", name: "Penal, Criminal and Regulatory", isActive: true },
  { id: "cat-6", name: "Agriculture", isActive: true },
  { id: "cat-7", name: "Education", isActive: true },
  { id: "cat-8", name: "Health", isActive: true },
  { id: "cat-9", name: "Peace and Order", isActive: true },
  { id: "cat-10", name: "Sports / Amusement", isActive: true },
  { id: "cat-11", name: "Tourism", isActive: true },
  { id: "cat-12", name: "Monetary Aide and other requests", isActive: true },
  { id: "cat-13", name: "Land Use / Zoning", isActive: true },
  { id: "cat-14", name: "Municipal Lots", isActive: true },
  { id: "cat-15", name: "Waterworks", isActive: true },
  { id: "cat-16", name: "Administrative Matters", isActive: true },
  { id: "cat-17", name: "History and Heritage", isActive: true },
  { id: "cat-18", name: "Budget", isActive: true },
  { id: "cat-19", name: "Loans and other Fiscal Matters", isActive: true },
  { id: "cat-20", name: "Celebrations", isActive: true },
  { id: "cat-21", name: "Sisterhood Agreement", isActive: true },
  { id: "cat-22", name: "Women and Children / PWD / Senior Citizen", isActive: true },
  { id: "cat-23", name: "Information Technology", isActive: true },
  { id: "cat-24", name: "MOA / MOU / Usufruct / Contracts & Agreements", isActive: true },
  { id: "cat-25", name: "Coastal Management", isActive: true },
  { id: "cat-26", name: "Traffic Matters", isActive: true },
  { id: "cat-27", name: "NGO / PO Accreditation", isActive: true },
  { id: "cat-28", name: "Purok System", isActive: true },
  { id: "cat-29", name: "Risk Reduction", isActive: true },
  { id: "cat-30", name: "Transportation", isActive: true },
  { id: "cat-31", name: "Franchise", isActive: true },
];

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@panglao.gov.ph",
    role: "sys_admin",
    isActive: true,
    lastLogin: new Date("2026-02-17T08:00:00"),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-2",
    name: "Maria Santos",
    email: "maria.santos@panglao.gov.ph",
    role: "sb_secretary",
    isActive: true,
    lastLogin: new Date("2026-02-18T09:30:00"),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user-3",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@panglao.gov.ph",
    role: "sb_member",
    isActive: true,
    lastLogin: new Date("2026-02-16T14:00:00"),
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "user-4",
    name: "Ana Reyes",
    email: "ana.reyes@panglao.gov.ph",
    role: "digitization_assistant",
    isActive: true,
    lastLogin: new Date("2026-02-18T07:45:00"),
    createdAt: new Date("2024-03-01"),
  },
];

export const mockOrdinances: LegislativeDocument[] = [
  {
    id: "ord-1",
    documentType: "ordinance",
    proposedNumber: "2026-01",
    approvedNumber: "2026-01",
    seriesYear: 2026,
    title:
      "An Ordinance Regulating the Operation of Tourist Transport Services in the Municipality of Panglao",
    authorSponsor: "Hon. Ricardo Mendoza",
    category: "Tourism",
    dateEnacted: new Date("2026-01-15"),
    dateApproved: new Date("2026-01-20"),
    publicationInfo: "Published in Panglao Gazette, Vol. 12, Issue 1",
    remarks: "Effective immediately upon approval",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [
      {
        versionNumber: 1,
        pdfUrl: SAMPLE_PDF_SNORKELING,
        uploadedBy: "Maria Santos",
        uploadedAt: new Date("2026-01-10"),
        notes: "Initial upload",
      },
    ],
    timeline: [
      { status: "Scanned", date: new Date("2026-01-10"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-01-12"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2026-01-15"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-01-20"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2026-01-22"), performedBy: "Maria Santos" },
    ],
    currentOffice: "SB Office",
    assignedTo: "Maria Santos",
    stage: "Published",
    routingHistory: [
      { office: "SB Office", assignedTo: "Maria Santos", stage: "Published", date: new Date("2026-01-22"), remark: "Published to portal", committee: "Committee on Economic Development and Social Enterprise", userEmail: "maria.santos@panglao.gov.ph" },
      { office: "Mayor's Office", assignedTo: "Municipal Mayor", stage: "For Signature", date: new Date("2026-01-20"), committee: "Committee on Economic Development and Social Enterprise", userEmail: "maria.santos@panglao.gov.ph" },
      { office: "SB Office", assignedTo: "Maria Santos", stage: "For Review", date: new Date("2026-01-12"), committee: "Committee on Economic Development and Social Enterprise", userEmail: "maria.santos@panglao.gov.ph" },
    ],
    sessionDate: new Date("2026-01-15"),
    referralType: "letter",
    trackingSubject: "Letter regarding Tourist Transport Services Regulation",
    assignedCommittee: "Committee on Economic Development and Social Enterprise",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-22"),
  },
  {
    id: "ord-2",
    documentType: "ordinance",
    proposedNumber: "2026-02",
    approvedNumber: "2026-02",
    seriesYear: 2026,
    title:
      "An Ordinance Imposing Environmental Protection Fees for Visitors Accessing Protected Marine Areas",
    authorSponsor: "Hon. Elena Villareal",
    category: "Environment",
    dateEnacted: new Date("2026-01-28"),
    dateApproved: new Date("2026-02-01"),
    publicationInfo: "Published in Panglao Gazette, Vol. 12, Issue 2",
    remarks: "",
    notes: "Aligned with DENR guidelines",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    versions: [
      {
        versionNumber: 1,
        pdfUrl: SAMPLE_PDF_TRICYCLE,
        uploadedBy: "Maria Santos",
        uploadedAt: new Date("2026-01-25"),
        notes: "Initial upload",
      },
    ],
    timeline: [
      { status: "Scanned", date: new Date("2026-01-25"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-01-26"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2026-01-28"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-02-01"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2026-02-03"), performedBy: "Maria Santos" },
    ],
    currentOffice: "SB Office",
    assignedTo: "Maria Santos",
    stage: "Published",
    routingHistory: [
      { office: "SB Office", assignedTo: "Maria Santos", stage: "Published", date: new Date("2026-02-03"), remark: "Published to portal", committee: "Committee on Environment", userEmail: "maria.santos@panglao.gov.ph" },
      { office: "Mayor's Office", assignedTo: "Municipal Mayor", stage: "For Signature", date: new Date("2026-02-01"), committee: "Committee on Environment", userEmail: "maria.santos@panglao.gov.ph" },
    ],
    sessionDate: new Date("2026-01-28"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Environmental Protection Fees",
    assignedCommittee: "Committee on Environment",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-02-03"),
  },
  {
    id: "ord-3",
    documentType: "ordinance",
    proposedNumber: "2026-03",
    approvedNumber: "",
    seriesYear: 2026,
    title:
      "An Ordinance Establishing the Municipal Scholarship Program for Underprivileged Youth",
    authorSponsor: "Hon. Pedro Castillo",
    category: "Education",
    dateEnacted: new Date("2026-02-05"),
    dateApproved: new Date("2026-02-10"),
    publicationInfo: "",
    remarks: "Pending committee review",
    notes: "",
    repealsAmendments: "",
    status: "draft",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [
      {
        versionNumber: 1,
        pdfUrl: SAMPLE_PDF_SNORKELING,
        uploadedBy: "Ana Reyes",
        uploadedAt: new Date("2026-02-05"),
        notes: "Initial scan",
      },
    ],
    timeline: [
      { status: "Scanned", date: new Date("2026-02-05"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-02-06"), performedBy: "Maria Santos" },
    ],
    currentOffice: "Committee on Finance",
    assignedTo: "Hon. Ricardo Mendoza",
    stage: "For Review",
    routingHistory: [
      { office: "Committee on Finance", assignedTo: "Hon. Ricardo Mendoza", stage: "For Review", date: new Date("2026-02-07"), remark: "Referred for budget review", committee: "Committee on Finance, Budget and Appropriations", userEmail: "maria.santos@panglao.gov.ph" },
      { office: "SB Office", assignedTo: "Maria Santos", stage: "Drafted", date: new Date("2026-02-06"), committee: "Committee on Finance, Budget and Appropriations", userEmail: "maria.santos@panglao.gov.ph" },
    ],
    sessionDate: new Date("2026-02-05"),
    referralType: "draft_ordinance",
    trackingSubject: "Draft Ordinance on Municipal Scholarship Program",
    assignedCommittee: "Committee on Finance, Budget and Appropriations",
    legislativeOutput: "Under Review",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-4",
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-02-06"),
  },
  {
    id: "ord-4",
    documentType: "ordinance",
    proposedNumber: "2025-15",
    approvedNumber: "2025-15",
    seriesYear: 2025,
    title:
      "An Ordinance Regulating the Use of Single-Use Plastics Within the Municipality",
    authorSponsor: "Hon. Elena Villareal",
    category: "Environment",
    dateEnacted: new Date("2025-10-15"),
    dateApproved: new Date("2025-10-20"),
    publicationInfo: "Published in Panglao Gazette, Vol. 11, Issue 10",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [
      {
        versionNumber: 1,
        pdfUrl: SAMPLE_PDF_SNORKELING,
        uploadedBy: "Maria Santos",
        uploadedAt: new Date("2025-10-10"),
        notes: "Initial upload",
      },
    ],
    timeline: [
      { status: "Scanned", date: new Date("2025-10-10"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-10-11"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-10-14"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-10-20"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-10-22"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-10-15"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Single-Use Plastics Regulation",
    assignedCommittee: "Committee on Environment",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-10-10"),
    updatedAt: new Date("2025-10-22"),
  },
  {
    id: "ord-5",
    documentType: "ordinance",
    proposedNumber: "2025-12",
    approvedNumber: "2025-12",
    seriesYear: 2025,
    title:
      "An Ordinance Approving the Annual Budget of the Municipality of Panglao for Fiscal Year 2026",
    authorSponsor: "Hon. Ricardo Mendoza",
    category: "Budget",
    dateEnacted: new Date("2025-09-01"),
    dateApproved: new Date("2025-09-15"),
    publicationInfo: "Published in Panglao Gazette, Vol. 11, Issue 9",
    remarks: "",
    notes: "Annual appropriations ordinance",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [
      {
        versionNumber: 1,
        pdfUrl: SAMPLE_PDF_SNORKELING,
        uploadedBy: "Maria Santos",
        uploadedAt: new Date("2025-08-28"),
        notes: "Initial upload",
      },
    ],
    timeline: [
      { status: "Scanned", date: new Date("2025-08-28"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-08-29"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-09-01"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-09-15"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-09-18"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-09-01"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Annual Municipal Budget for FY 2026",
    assignedCommittee: "Committee on Finance, Budget and Appropriations",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-08-28"),
    updatedAt: new Date("2025-09-18"),
  },
  {
    id: "ord-6",
    documentType: "ordinance",
    proposedNumber: "2025-08",
    approvedNumber: "2025-08",
    seriesYear: 2025,
    title: "An Ordinance Creating the Panglao Municipal Health Emergency Response Team",
    authorSponsor: "Hon. Lourdes Garcia",
    category: "Health",
    dateEnacted: new Date("2025-06-10"),
    dateApproved: new Date("2025-06-20"),
    publicationInfo: "Published in Panglao Gazette, Vol. 11, Issue 6",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2025-06-05"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-06-08"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-06-12"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-06-18"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-06-22"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-06-10"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance Creating Municipal Health Emergency Response Team",
    assignedCommittee: "Committee on Health and Social Services",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-06-05"),
    updatedAt: new Date("2025-06-22"),
  },
  {
    id: "ord-7",
    documentType: "ordinance",
    proposedNumber: "2025-05",
    approvedNumber: "2025-05",
    seriesYear: 2025,
    title:
      "An Ordinance Mandating the Establishment of Barangay-Level Disaster Preparedness Committees",
    authorSponsor: "Hon. Pedro Castillo",
    category: "Peace and Order",
    dateEnacted: new Date("2025-04-01"),
    dateApproved: new Date("2025-04-10"),
    publicationInfo: "Published in Panglao Gazette, Vol. 11, Issue 4",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2025-03-28"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-03-30"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-04-02"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-04-08"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-04-12"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-04-01"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Disaster Preparedness Committees",
    assignedCommittee: "Committee on Peace & Order and Public Safety",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-03-28"),
    updatedAt: new Date("2025-04-12"),
  },
  {
    id: "ord-8",
    documentType: "ordinance",
    proposedNumber: "2024-20",
    approvedNumber: "2024-20",
    seriesYear: 2024,
    title:
      "An Ordinance Providing for the Comprehensive Land Use Plan of the Municipality of Panglao",
    authorSponsor: "Hon. Ricardo Mendoza",
    category: "Land Use / Zoning",
    dateEnacted: new Date("2024-11-01"),
    dateApproved: new Date("2024-11-15"),
    publicationInfo: "Published in Panglao Gazette, Vol. 10, Issue 11",
    remarks: "",
    notes: "10-year comprehensive plan",
    repealsAmendments: "Repeals Ordinance No. 2014-05",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2024-10-25"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2024-10-28"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2024-11-01"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2024-11-12"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2024-11-18"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2024-11-01"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Municipal Road Improvement Program",
    assignedCommittee: "Committee on Human Settlement, Land Use & Development",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2024-10-25"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "ord-9",
    documentType: "ordinance",
    proposedNumber: "2024-14",
    approvedNumber: "2024-14",
    seriesYear: 2024,
    title:
      "An Ordinance Providing Tax Incentives for Local Businesses Employing Persons with Disabilities",
    authorSponsor: "Hon. Lourdes Garcia",
    category: "Women and Children / PWD / Senior Citizen",
    dateEnacted: new Date("2024-08-05"),
    dateApproved: new Date("2024-08-15"),
    publicationInfo: "Published in Panglao Gazette, Vol. 10, Issue 8",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2024-08-01"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2024-08-05"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2024-08-10"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2024-08-14"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2024-08-18"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2024-08-05"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Tax Incentives for PWD Employment",
    assignedCommittee: "Committee on Health and Social Services",
    legislativeOutput: "Ordinance Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-18"),
  },
  {
    id: "ord-10",
    documentType: "ordinance",
    proposedNumber: "2026-04",
    approvedNumber: "2026-04",
    seriesYear: 2026,
    title:
      "An Ordinance Establishing the Municipal Road Improvement and Maintenance Program",
    authorSponsor: "Hon. Pedro Castillo",
    category: "Infrastructure",
    dateEnacted: new Date("2026-02-10"),
    dateApproved: new Date("2026-02-15"),
    publicationInfo: "",
    remarks: "Under review",
    notes: "",
    repealsAmendments: "",
    status: "approved",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2026-02-08"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-02-09"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-02-15"), performedBy: "Maria Santos" },
    ],
    currentOffice: "Mayor's Office",
    assignedTo: "Municipal Mayor",
    stage: "for_signature",
    routingHistory: [
      { office: "Mayor's Office", assignedTo: "Municipal Mayor", stage: "for_signature", date: new Date("2026-02-15"), remark: "Forwarded for approval", committee: "Committee on Public Works, Infrastructure & Public Utilities", userEmail: "maria.santos@panglao.gov.ph" },
      { office: "SB Office", assignedTo: "Maria Santos", stage: "for_approval", date: new Date("2026-02-14"), committee: "Committee on Public Works, Infrastructure & Public Utilities", userEmail: "maria.santos@panglao.gov.ph" },
    ],
    sessionDate: new Date("2026-02-10"),
    referralType: "brgy_ordinance",
    trackingSubject: "Brgy Ordinance on Municipal Road Improvement and Maintenance",
    assignedCommittee: "Committee on Public Works, Infrastructure & Public Utilities",
    legislativeOutput: "Ordinance Approved",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-02-15"),
  },
];

export const mockResolutions: LegislativeDocument[] = [
  {
    id: "res-1",
    documentType: "resolution",
    proposedNumber: "2026-01",
    approvedNumber: "2026-01",
    seriesYear: 2026,
    title:
      "A Resolution Expressing Support for the National Government's Eco-Tourism Development Program",
    authorSponsor: "Hon. Elena Villareal",
    category: "Tourism",
    dateEnacted: new Date("2026-01-10"),
    dateApproved: new Date("2026-01-12"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2026-01-08"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-01-10"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2026-01-12"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-01-13"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2026-01-14"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2026-01-10"),
    referralType: "letter",
    trackingSubject: "Letter Supporting National Eco-Tourism Development Program",
    assignedCommittee: "Committee on Economic Development and Social Enterprise",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-01-14"),
  },
  {
    id: "res-2",
    documentType: "resolution",
    proposedNumber: "2026-02",
    approvedNumber: "2026-02",
    seriesYear: 2026,
    title:
      "A Resolution Requesting the DPWH to Expedite the Construction of the Panglao Bypass Road",
    authorSponsor: "Hon. Pedro Castillo",
    category: "Infrastructure",
    dateEnacted: new Date("2026-01-20"),
    dateApproved: new Date("2026-01-22"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2026-01-18"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-01-20"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2026-01-22"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-01-23"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2026-01-24"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2026-01-20"),
    referralType: "memorandum",
    trackingSubject: "Memorandum Requesting DPWH Panglao Bypass Road Expedited Construction",
    assignedCommittee: "Committee on Public Works, Infrastructure & Public Utilities",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-01-18"),
    updatedAt: new Date("2026-01-24"),
  },
  {
    id: "res-3",
    documentType: "resolution",
    proposedNumber: "2026-03",
    approvedNumber: "",
    seriesYear: 2026,
    title:
      "A Resolution Commending the Panglao National High School for Winning the Regional Science Competition",
    authorSponsor: "Hon. Lourdes Garcia",
    category: "Education",
    dateEnacted: new Date("2026-02-01"),
    dateApproved: new Date("2026-02-01"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "draft",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Drafted", date: new Date("2026-02-01"), performedBy: "Maria Santos" },
    ],
    currentOffice: "SB Office",
    assignedTo: "Maria Santos",
    stage: "for_approval",
    routingHistory: [
      { office: "SB Office", assignedTo: "Maria Santos", stage: "for_approval", date: new Date("2026-02-01"), committee: "Committee on Education", userEmail: "maria.santos@panglao.gov.ph" },
    ],
    sessionDate: new Date("2026-02-01"),
    referralType: "draft_resolutions",
    trackingSubject: "Draft Resolution Commending Panglao National High School Science Competition",
    assignedCommittee: "Committee on Education",
    legislativeOutput: "Under Review",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-01-30"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "res-4",
    documentType: "resolution",
    proposedNumber: "2025-20",
    approvedNumber: "2025-20",
    seriesYear: 2025,
    title:
      "A Resolution Adopting the Municipal Disaster Risk Reduction and Management Plan for 2025-2030",
    authorSponsor: "Hon. Pedro Castillo",
    category: "Peace and Order",
    dateEnacted: new Date("2025-11-05"),
    dateApproved: new Date("2025-11-10"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2025-11-01"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-11-04"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-11-06"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-11-10"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-11-12"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-11-05"),
    referralType: "brgy_resolution",
    trackingSubject: "Brgy Resolution Adopting Disaster Risk Reduction and Management Plan",
    assignedCommittee: "Committee on Peace & Order and Public Safety",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-12"),
  },
  {
    id: "res-5",
    documentType: "resolution",
    proposedNumber: "2025-15",
    approvedNumber: "2025-15",
    seriesYear: 2025,
    title:
      "A Resolution Authorizing the Municipal Mayor to Enter into a Memorandum of Agreement with the Department of Health",
    authorSponsor: "Hon. Lourdes Garcia",
    category: "Health",
    dateEnacted: new Date("2025-08-10"),
    dateApproved: new Date("2025-08-15"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2025-08-08"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-08-10"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-08-12"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-08-15"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-08-18"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-08-10"),
    referralType: "memorandum",
    trackingSubject: "Memorandum Authorizing MOA with Department of Health",
    assignedCommittee: "Committee on Health and Social Services",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-08-08"),
    updatedAt: new Date("2025-08-18"),
  },
  {
    id: "res-6",
    documentType: "resolution",
    proposedNumber: "2025-10",
    approvedNumber: "2025-10",
    seriesYear: 2025,
    title:
      "A Resolution Endorsing the Creation of Marine Protected Areas Along the Panglao Coastline",
    authorSponsor: "Hon. Elena Villareal",
    category: "Environment",
    dateEnacted: new Date("2025-05-20"),
    dateApproved: new Date("2025-05-25"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2025-05-18"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2025-05-20"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2025-05-22"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2025-05-25"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2025-05-28"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2025-05-20"),
    referralType: "brgy_resolution",
    trackingSubject: "Brgy Resolution Endorsing Marine Protected Areas Creation",
    assignedCommittee: "Committee on Environment",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2025-05-18"),
    updatedAt: new Date("2025-05-28"),
  },
  {
    id: "res-7",
    documentType: "resolution",
    proposedNumber: "2026-04",
    approvedNumber: "2026-04",
    seriesYear: 2026,
    title:
      "A Resolution Declaring February as Municipal Tourism Month in Panglao",
    authorSponsor: "Hon. Ricardo Mendoza",
    category: "Tourism",
    dateEnacted: new Date("2026-02-05"),
    dateApproved: new Date("2026-02-08"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "approved",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2026-02-03"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2026-02-05"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2026-02-06"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2026-02-08"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2026-02-05"),
    referralType: "draft_resolutions",
    trackingSubject: "Draft Resolution Declaring February as Municipal Tourism Month",
    assignedCommittee: "Committee on Economic Development and Social Enterprise",
    legislativeOutput: "Resolution Approved",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2026-02-03"),
    updatedAt: new Date("2026-02-08"),
  },
  {
    id: "res-8",
    documentType: "resolution",
    proposedNumber: "2024-25",
    approvedNumber: "2024-25",
    seriesYear: 2024,
    title:
      "A Resolution Allocating Additional Funds for the Senior Citizens Welfare Program",
    authorSponsor: "Hon. Lourdes Garcia",
    category: "Women and Children / PWD / Senior Citizen",
    dateEnacted: new Date("2024-12-10"),
    dateApproved: new Date("2024-12-15"),
    publicationInfo: "",
    remarks: "",
    notes: "",
    repealsAmendments: "",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    versions: [],
    timeline: [
      { status: "Scanned", date: new Date("2024-12-08"), performedBy: "Ana Reyes" },
      { status: "Drafted", date: new Date("2024-12-10"), performedBy: "Maria Santos" },
      { status: "Validated", date: new Date("2024-12-12"), performedBy: "Maria Santos" },
      { status: "Approved", date: new Date("2024-12-15"), performedBy: "Maria Santos" },
      { status: "Published", date: new Date("2024-12-18"), performedBy: "Maria Santos" },
    ],
    sessionDate: new Date("2024-12-10"),
    referralType: "brgy_resolution",
    trackingSubject: "Brgy Resolution Allocating Funds for Senior Citizens Welfare",
    assignedCommittee: "Committee on Health and Social Services",
    legislativeOutput: "Resolution Passed",
    lastUpdatedByEmail: "maria.santos@panglao.gov.ph",
    createdBy: "user-2",
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-18"),
  },
];

export const mockMinutes: SessionMinutes[] = [
  {
    id: "min-1",
    documentType: "minutes",
    sessionDate: new Date("2026-01-13"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2026-01-14"),
    updatedAt: new Date("2026-01-16"),
  },
  {
    id: "min-2",
    documentType: "minutes",
    sessionDate: new Date("2026-01-27"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    createdBy: "user-2",
    createdAt: new Date("2026-01-28"),
    updatedAt: new Date("2026-01-30"),
  },
  {
    id: "min-3",
    documentType: "minutes",
    sessionDate: new Date("2026-02-03"),
    sessionType: "special",
    status: "approved",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2026-02-04"),
    updatedAt: new Date("2026-02-06"),
  },
  {
    id: "min-4",
    documentType: "minutes",
    sessionDate: new Date("2026-02-10"),
    sessionType: "regular",
    status: "approved",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2026-02-11"),
    updatedAt: new Date("2026-02-13"),
  },
  {
    id: "min-5",
    documentType: "minutes",
    sessionDate: new Date("2026-02-17"),
    sessionType: "regular",
    status: "draft",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2026-02-18"),
    updatedAt: new Date("2026-02-18"),
  },
  {
    id: "min-6",
    documentType: "minutes",
    sessionDate: new Date("2026-03-03"),
    sessionType: "regular",
    status: "draft",
    isPublic: false,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2026-03-04"),
    updatedAt: new Date("2026-03-04"),
  },
  // 2025
  {
    id: "min-7",
    documentType: "minutes",
    sessionDate: new Date("2025-01-14"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-17"),
  },
  {
    id: "min-8",
    documentType: "minutes",
    sessionDate: new Date("2025-02-11"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    createdBy: "user-2",
    createdAt: new Date("2025-02-12"),
    updatedAt: new Date("2025-02-14"),
  },
  {
    id: "min-9",
    documentType: "minutes",
    sessionDate: new Date("2025-06-10"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2025-06-11"),
    updatedAt: new Date("2025-06-13"),
  },
  {
    id: "min-10",
    documentType: "minutes",
    sessionDate: new Date("2025-11-04"),
    sessionType: "special",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2025-11-07"),
  },
  // 2024
  {
    id: "min-11",
    documentType: "minutes",
    sessionDate: new Date("2024-01-09"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "min-12",
    documentType: "minutes",
    sessionDate: new Date("2024-04-02"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    createdBy: "user-2",
    createdAt: new Date("2024-04-03"),
    updatedAt: new Date("2024-04-05"),
  },
  {
    id: "min-13",
    documentType: "minutes",
    sessionDate: new Date("2024-08-06"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2024-08-07"),
    updatedAt: new Date("2024-08-09"),
  },
  {
    id: "min-14",
    documentType: "minutes",
    sessionDate: new Date("2024-12-03"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2024-12-04"),
    updatedAt: new Date("2024-12-06"),
  },
  // 2023
  {
    id: "min-15",
    documentType: "minutes",
    sessionDate: new Date("2023-02-07"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2023-02-08"),
    updatedAt: new Date("2023-02-10"),
  },
  {
    id: "min-16",
    documentType: "minutes",
    sessionDate: new Date("2023-05-09"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    createdBy: "user-2",
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2023-05-12"),
  },
  {
    id: "min-17",
    documentType: "minutes",
    sessionDate: new Date("2023-09-05"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2023-09-06"),
    updatedAt: new Date("2023-09-08"),
  },
  // 2022
  {
    id: "min-18",
    documentType: "minutes",
    sessionDate: new Date("2022-01-11"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2022-01-12"),
    updatedAt: new Date("2022-01-14"),
  },
  {
    id: "min-19",
    documentType: "minutes",
    sessionDate: new Date("2022-04-05"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_TRICYCLE,
    createdBy: "user-2",
    createdAt: new Date("2022-04-06"),
    updatedAt: new Date("2022-04-08"),
  },
  {
    id: "min-20",
    documentType: "minutes",
    sessionDate: new Date("2022-08-02"),
    sessionType: "regular",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_EUF,
    createdBy: "user-2",
    createdAt: new Date("2022-08-03"),
    updatedAt: new Date("2022-08-05"),
  },
  {
    id: "min-21",
    documentType: "minutes",
    sessionDate: new Date("2022-11-08"),
    sessionType: "special",
    status: "published",
    isPublic: true,
    pdfUrl: SAMPLE_PDF_SNORKELING,
    createdBy: "user-2",
    createdAt: new Date("2022-11-09"),
    updatedAt: new Date("2022-11-11"),
  },
];

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: new Date("2026-02-18T09:30:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "login",
    details: "User logged in",
  },
  {
    id: "log-2",
    timestamp: new Date("2026-02-18T09:35:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "upload",
    documentId: "ord-10",
    documentTitle: "Ordinance 2026-04 - Road Improvement",
    details: "Uploaded new ordinance document",
  },
  {
    id: "log-3",
    timestamp: new Date("2026-02-17T14:20:00"),
    userId: "user-4",
    userName: "Ana Reyes",
    action: "upload",
    documentId: "ord-3",
    documentTitle: "Ordinance 2026-03 - Scholarship Program",
    details: "Scanned and uploaded document",
  },
  {
    id: "log-4",
    timestamp: new Date("2026-02-17T11:00:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "publish",
    documentId: "ord-2",
    documentTitle: "Ordinance 2026-02 - Environmental Protection Fees",
    details: "Published ordinance to public portal",
  },
  {
    id: "log-5",
    timestamp: new Date("2026-02-16T16:45:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "edit",
    documentId: "res-7",
    documentTitle: "Resolution 2026-04 - Tourism Month",
    details: "Updated metadata and remarks",
  },
  {
    id: "log-6",
    timestamp: new Date("2026-02-16T14:00:00"),
    userId: "user-3",
    userName: "Juan Dela Cruz",
    action: "login",
    details: "User logged in",
  },
  {
    id: "log-7",
    timestamp: new Date("2026-02-15T10:30:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "upload",
    documentId: "min-5",
    documentTitle: "Minutes - Feb 17 Regular Session",
    details: "Uploaded session minutes",
  },
  {
    id: "log-8",
    timestamp: new Date("2026-02-14T09:00:00"),
    userId: "user-1",
    userName: "Admin User",
    action: "login",
    details: "User logged in",
  },
  {
    id: "log-9",
    timestamp: new Date("2026-02-13T15:20:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "edit",
    documentId: "min-4",
    documentTitle: "Minutes - Feb 10 Regular Session",
    details: "Updated session minutes status to approved",
  },
  {
    id: "log-10",
    timestamp: new Date("2026-02-12T10:15:00"),
    userId: "user-4",
    userName: "Ana Reyes",
    action: "upload",
    documentId: "res-3",
    documentTitle: "Resolution 2026-03 - Science Competition",
    details: "Scanned and uploaded document",
  },
  {
    id: "log-11",
    timestamp: new Date("2026-02-11T08:30:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "publish",
    documentId: "res-2",
    documentTitle: "Resolution 2026-02 - Bypass Road",
    details: "Published resolution to public portal",
  },
  {
    id: "log-12",
    timestamp: new Date("2026-02-10T14:00:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "upload",
    documentId: "min-4",
    documentTitle: "Minutes - Feb 10 Regular Session",
    details: "Uploaded session minutes",
  },
  {
    id: "log-13",
    timestamp: new Date("2026-02-09T11:30:00"),
    userId: "user-1",
    userName: "Admin User",
    action: "edit",
    details: "Updated system settings - backup schedule",
  },
  {
    id: "log-14",
    timestamp: new Date("2026-02-08T09:00:00"),
    userId: "user-4",
    userName: "Ana Reyes",
    action: "login",
    details: "User logged in",
  },
  {
    id: "log-15",
    timestamp: new Date("2026-02-07T16:00:00"),
    userId: "user-2",
    userName: "Maria Santos",
    action: "logout",
    details: "User logged out",
  },
];

export const mockRequests: DocumentRequest[] = [
  {
    id: "req-1",
    requestor: "Brgy. Captain Jose Dela Cruz",
    documentId: "ord-5",
    documentTitle: "Ordinance 2025-12 - Annual Budget FY 2026",
    dateRequested: new Date("2026-02-10"),
    dateReleased: new Date("2026-02-12"),
    status: "released",
    processedBy: "Maria Santos",
  },
  {
    id: "req-2",
    requestor: "Ms. Patricia Lim - Tourism Office",
    documentId: "ord-1",
    documentTitle: "Ordinance 2026-01 - Tourist Transport",
    dateRequested: new Date("2026-02-14"),
    status: "submitted",
    processedBy: "Maria Santos",
  },
  {
    id: "req-3",
    requestor: "Atty. Roberto Gonzales",
    documentId: "ord-8",
    documentTitle: "Ordinance 2024-20 - Comprehensive Land Use Plan",
    dateRequested: new Date("2026-02-15"),
    dateReleased: new Date("2026-02-16"),
    status: "released",
    processedBy: "Maria Santos",
  },
  {
    id: "req-4",
    requestor: "Ms. Liza Tan - Barangay Alona",
    documentId: "res-2",
    documentTitle: "Resolution 2026-02 - Bypass Road",
    dateRequested: new Date("2026-02-18"),
    status: "approved",
    processedBy: "Maria Santos",
  },
];

const SB_MEMBER_IMAGE = "/images/sb-member-placeholder.png";

const formatCommitteePersonName = (name: string) =>
  name === "Daisy M. Delambaca"
    ? "Vice Mayor Daisy M. Delambaca"
    : `Hon. ${name}`;

export const mockSBMembers: SBMember[] = [
  {
    id: "sb-1",
    name: "Daisy M. Delambaca",
    position: "Vice Mayor",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Tourism and Cultural Heritage",
      "Committee on Women, Children and Family",
      "Committee on Human Rights",
      "Committee on Sisterhood and International Relations",
    ],
    imageUrl: "/images/sb/vm-delambaca.webp",
  },
  {
    id: "sb-2",
    name: "Francis Erick D. Delambaca",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Rules, Privileges, and Accreditation",
      "Committee on Finance, Budget and Appropriations",
      "Committee on Cultural Communities",
      "Committee on Youth and Sports Development",
      "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
      "Committee on Labor and Employment",
      "Committee on Human Rights",
      "Committee on Ways and Means",
      "Committee on Games & Amusement",
      "Committee on Laws, Resolutions, Ordinances, and Justice",
      "Committee on Information and Media Affairs",
    ],
    imageUrl: "/images/sb/delambaca.webp",
  },
  {
    id: "sb-3",
    name: "Amira Alia M. Caindec",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Women, Children and Family",
      "Committee on Health and Social Services",
      "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
      "Committee on Youth and Sports Development",
      "Committee on Labor and Employment",
      "Committee on Human Rights",
      "Committee on Science and Technology",
      "Committee on Ways and Means",
      "Committee on Games & Amusement",
      "Committee on Human Settlement, Planning & Development",
      "Committee on Laws, Resolutions, Ordinances, and Justice",
      "Committee on Government Organizations and Non-Government Organizations",
      "Committee on Sisterhood and International Relations",
      "Committee on Beautification, Streets, Parks & Playgrounds",
      "Committee on Information and Media Affairs",
      "Committee on Cooperative and Livelihood",
    ],
    imageUrl: "/images/sb/caindec.webp",
  },
  {
    id: "sb-4",
    name: "Analyn H. Casane",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Rules, Privileges, and Accreditation",
      "Committee on Education",
      "Committee on Tourism and Cultural Heritage",
      "Committee on Women, Children and Family",
      "Committee on Health and Social Services",
      "Committee on Public Works, Infrastructure & Public Utilities",
      "Committee on Cultural Communities",
      "Committee on Natural Resources & Environmental Protection",
      "Committee on Youth and Sports Development",
      "Committee on Human Rights",
      "Committee on Trade, Commerce, and Industry",
      "Committee on Ways and Means",
      "Committee on Human Settlement, Planning & Development",
      "Committee on Peace & Order, and Public Safety",
      "Committee on Sisterhood and International Relations",
      "Committee on Beautification, Streets, Parks & Playgrounds",
      "Committee on Government Enterprises and Market",
      "Committee on Transportation",
    ],
    imageUrl: "/images/sb/casane.webp",
  },
  {
    id: "sb-5",
    name: "Albert G. Bompat",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Finance, Budget and Appropriations",
      "Committee on Education",
      "Committee on Tourism and Cultural Heritage",
      "Committee on Women, Children and Family",
      "Committee on Health and Social Services",
      "Committee on Public Works, Infrastructure & Public Utilities",
      "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
      "Committee on Natural Resources & Environmental Protection",
      "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
      "Committee on Trade, Commerce, and Industry",
      "Committee on Science and Technology",
      "Committee on Ways and Means",
      "Committee on Human Settlement, Planning & Development",
      "Committee on Laws, Resolutions, Ordinances, and Justice",
      "Committee on Government Organizations and Non-Government Organizations",
      "Committee on Sisterhood and International Relations",
      "Committee on Beautification, Streets, Parks & Playgrounds",
      "Committee on Information and Media Affairs",
      "Committee on Government Enterprises and Market",
      "Committee on Cooperative and Livelihood",
      "Committee on Transportation",
    ],
    imageUrl: "/images/sb/bompat.webp",
  },
  {
    id: "sb-6",
    name: "Alfonso C. Alcala",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Rules, Privileges, and Accreditation",
      "Committee on Finance, Budget and Appropriations",
      "Committee on Education",
      "Committee on Tourism and Cultural Heritage",
      "Committee on Health and Social Services",
      "Committee on Public Works, Infrastructure & Public Utilities",
      "Committee on Natural Resources & Environmental Protection",
      "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
      "Committee on Labor and Employment",
      "Committee on Trade, Commerce, and Industry",
      "Committee on Science and Technology",
      "Committee on Games & Amusement",
      "Committee on Laws, Resolutions, Ordinances, and Justice",
      "Committee on Government Organizations and Non-Government Organizations",
      "Committee on Beautification, Streets, Parks & Playgrounds",
    ],
    imageUrl: "/images/sb/alcala.webp",
  },
  {
    id: "sb-7",
    name: "Zinon G. Labaya",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Rules, Privileges, and Accreditation",
      "Committee on Finance, Budget and Appropriations",
      "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
      "Committee on Cultural Communities",
      "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
      "Committee on Ways and Means",
      "Committee on Games & Amusement",
      "Committee on Human Settlement, Planning & Development",
      "Committee on Peace & Order, and Public Safety",
      "Committee on Information and Media Affairs",
      "Committee on Government Enterprises and Market",
      "Committee on Cooperative and Livelihood",
      "Committee on Transportation",
    ],
    imageUrl: "/images/sb/labaya.webp",
  },
  {
    id: "sb-8",
    name: "Felix M. Fudolig",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Education",
      "Committee on Tourism and Cultural Heritage",
      "Committee on Health and Social Services",
      "Committee on Cultural Communities",
      "Committee on Natural Resources & Environmental Protection",
      "Committee on Youth and Sports Development",
      "Committee on Labor and Employment",
      "Committee on Trade, Commerce, and Industry",
      "Committee on Games & Amusement",
      "Committee on Human Settlement, Planning & Development",
      "Committee on Peace & Order, and Public Safety",
      "Committee on Government Organizations and Non-Government Organizations",
      "Committee on Information and Media Affairs",
      "Committee on Government Enterprises and Market",
      "Committee on Cooperative and Livelihood",
      "Committee on Transportation",
    ],
    imageUrl: "/images/sb/fudolig.webp",
  },
  {
    id: "sb-9",
    name: "Eduard G. Mejos",
    position: "SB Member",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Public Works, Infrastructure & Public Utilities",
      "Committee on Cultural Communities",
      "Committee on Natural Resources & Environmental Protection",
      "Committee on Human Rights",
      "Committee on Science and Technology",
      "Committee on Peace & Order, and Public Safety",
      "Committee on Government Enterprises and Market",
    ],
    imageUrl: "/images/sb/mejos.webp",
  },
  {
    id: "sb-10",
    name: "Fabian A. Aranaydo",
    position: "ABC President",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Rules, Privileges, and Accreditation",
      "Committee on Finance, Budget and Appropriations",
      "Committee on Education",
      "Committee on Women, Children and Family",
      "Committee on Public Works, Infrastructure & Public Utilities",
      "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
      "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
      "Committee on Trade, Commerce, and Industry",
      "Committee on Peace & Order, and Public Safety",
      "Committee on Sisterhood and International Relations",
      "Committee on Cooperative and Livelihood",
      "Committee on Transportation",
    ],
    imageUrl: "/images/sb/aranaydo.webp",
  },
  {
    id: "sb-11",
    name: "Renel Ryan B. Mila",
    position: "SK Federation President",
    committees: [
      "Committee of the Whole / En Banc",
      "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
      "Committee on Youth and Sports Development",
      "Committee on Labor and Employment",
      "Committee on Science and Technology",
      "Committee on Government Organizations and Non-Government Organizations",
      "Committee on Beautification, Streets, Parks & Playgrounds",
    ],
    imageUrl: "/images/sb/mila.webp",
  },
  {
    id: "sb-12",
    name: "Analyn A. Apduhan",
    position: "SB Secretary",
    committees: [
      "Committee of the Whole / En Banc",
    ],
    imageUrl: "/images/sb/apduhan.webp",
  },
];

export const mockSBStaff: { id: string; name: string; position: string; imageUrl?: string }[] = [
  { id: "staff-1", name: "Staff Member 1", position: "SB Staff" },
  { id: "staff-2", name: "Staff Member 2", position: "SB Staff" },
  { id: "staff-3", name: "Staff Member 3", position: "SB Staff" },
  { id: "staff-4", name: "Staff Member 4", position: "SB Staff" },
  { id: "staff-5", name: "Staff Member 5", position: "SB Staff" },
  { id: "staff-6", name: "Staff Member 6", position: "SB Staff" },
  { id: "staff-7", name: "Staff Member 7", position: "SB Staff" },
  { id: "staff-8", name: "Staff Member 8", position: "SB Staff" },
];

export const mockCommittees: Committee[] = [
  {
    id: "com-1",
    name: "Committee of the Whole / En Banc",
    chairman: formatCommitteePersonName("Daisy M. Delambaca"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Francis Erick D. Delambaca",
      "Alfonso C. Alcala",
      "Amira Alia M. Caindec",
      "Analyn H. Casane",
      "Zinon G. Labaya",
      "Felix M. Fudolig",
      "Eduard G. Mejos",
      "Fabian A. Aranaydo",
      "Renel Ryan B. Mila",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-2",
    name: "Committee on Rules, Privileges, and Accreditation",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Zinon G. Labaya",
      "Alfonso C. Alcala",
      "Fabian A. Aranaydo",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-3",
    name: "Committee on Finance, Budget and Appropriations",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Fabian A. Aranaydo",
      "Alfonso C. Alcala",
      "Zinon G. Labaya",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-4",
    name: "Committee on Education",
    chairman: formatCommitteePersonName("Albert G. Bompat"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Alfonso C. Alcala",
      "Fabian A. Aranaydo",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-5",
    name: "Committee on Tourism and Cultural Heritage",
    chairman: formatCommitteePersonName("Daisy M. Delambaca"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Alfonso C. Alcala",
      "Albert G. Bompat",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-6",
    name: "Committee on Women, Children and Family",
    chairman: formatCommitteePersonName("Daisy M. Delambaca"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Amira Alia M. Caindec",
      "Albert G. Bompat",
      "Fabian A. Aranaydo",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-7",
    name: "Committee on Health and Social Services",
    chairman: formatCommitteePersonName("Analyn H. Casane"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Albert G. Bompat",
      "Alfonso C. Alcala",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-8",
    name: "Committee on Public Works, Infrastructure & Public Utilities",
    chairman: formatCommitteePersonName("Alfonso C. Alcala"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Eduard G. Mejos",
      "Fabian A. Aranaydo",
      "Analyn H. Casane",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-9",
    name: "Committee on Barangay Affairs, Good Government, Public Ethics & Accountability",
    chairman: formatCommitteePersonName("Fabian A. Aranaydo"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Renel Ryan B. Mila",
      "Zinon G. Labaya",
      "Amira Alia M. Caindec",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-10",
    name: "Committee on Cultural Communities",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Felix M. Fudolig",
      "Eduard G. Mejos",
      "Zinon G. Labaya",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-11",
    name: "Committee on Natural Resources & Environmental Protection",
    chairman: formatCommitteePersonName("Albert G. Bompat"),
    viceChairman: formatCommitteePersonName("Eduard G. Mejos"),
    members: [
      "Alfonso C. Alcala",
      "Analyn H. Casane",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-12",
    name: "Committee on Youth and Sports Development",
    chairman: formatCommitteePersonName("Renel Ryan B. Mila"),
    viceChairman: formatCommitteePersonName("Felix M. Fudolig"),
    members: [
      "Francis Erick D. Delambaca",
      "Amira Alia M. Caindec",
      "Analyn H. Casane",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-13",
    name: "Committee on Agriculture, Fisheries, Food and Agrarian Reforms",
    chairman: formatCommitteePersonName("Zinon G. Labaya"),
    viceChairman: formatCommitteePersonName("Fabian A. Aranaydo"),
    members: [
      "Albert G. Bompat",
      "Francis Erick D. Delambaca",
      "Alfonso C. Alcala",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-14",
    name: "Committee on Labor and Employment",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Alfonso C. Alcala"),
    members: [
      "Amira Alia M. Caindec",
      "Felix M. Fudolig",
      "Renel Ryan B. Mila",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-15",
    name: "Committee on Human Rights",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Eduard G. Mejos"),
    members: [
      "Amira Alia M. Caindec",
      "Analyn H. Casane",
      "Daisy M. Delambaca",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-16",
    name: "Committee on Trade, Commerce, and Industry",
    chairman: formatCommitteePersonName("Analyn H. Casane"),
    viceChairman: formatCommitteePersonName("Alfonso C. Alcala"),
    members: [
      "Albert G. Bompat",
      "Felix M. Fudolig",
      "Fabian A. Aranaydo",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-17",
    name: "Committee on Science and Technology",
    chairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Renel Ryan B. Mila",
      "Eduard G. Mejos",
      "Alfonso C. Alcala",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-18",
    name: "Committee on Ways and Means",
    chairman: formatCommitteePersonName("Zinon G. Labaya"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Amira Alia M. Caindec",
      "Albert G. Bompat",
      "Francis Erick D. Delambaca",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-19",
    name: "Committee on Games & Amusement",
    chairman: formatCommitteePersonName("Zinon G. Labaya"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Francis Erick D. Delambaca",
      "Alfonso C. Alcala",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-20",
    name: "Committee on Human Settlement, Planning & Development",
    chairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Felix M. Fudolig",
      "Analyn H. Casane",
      "Zinon G. Labaya",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-21",
    name: "Committee on Laws, Resolutions, Ordinances, and Justice",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Analyn H. Casane",
      "Alfonso C. Alcala",
      "Albert G. Bompat",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-22",
    name: "Committee on Peace & Order, and Public Safety",
    chairman: formatCommitteePersonName("Eduard G. Mejos"),
    viceChairman: formatCommitteePersonName("Analyn H. Casane"),
    members: [
      "Zinon G. Labaya",
      "Fabian A. Aranaydo",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-23",
    name: "Committee on Government Organizations and Non-Government Organizations",
    chairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Felix M. Fudolig",
      "Renel Ryan B. Mila",
      "Alfonso C. Alcala",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-24",
    name: "Committee on Sisterhood and International Relations",
    chairman: formatCommitteePersonName("Daisy M. Delambaca"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Analyn H. Casane",
      "Fabian A. Aranaydo",
      "Albert G. Bompat",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-25",
    name: "Committee on Beautification, Streets, Parks & Playgrounds",
    chairman: formatCommitteePersonName("Analyn H. Casane"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Alfonso C. Alcala",
      "Albert G. Bompat",
      "Renel Ryan B. Mila",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-26",
    name: "Committee on Information and Media Affairs",
    chairman: formatCommitteePersonName("Francis Erick D. Delambaca"),
    viceChairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    members: [
      "Zinon G. Labaya",
      "Albert G. Bompat",
      "Felix M. Fudolig",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-27",
    name: "Committee on Government Enterprises and Market",
    chairman: formatCommitteePersonName("Zinon G. Labaya"),
    viceChairman: formatCommitteePersonName("Felix M. Fudolig"),
    members: [
      "Analyn H. Casane",
      "Albert G. Bompat",
      "Eduard G. Mejos",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-28",
    name: "Committee on Cooperative and Livelihood",
    chairman: formatCommitteePersonName("Amira Alia M. Caindec"),
    viceChairman: formatCommitteePersonName("Albert G. Bompat"),
    members: [
      "Felix M. Fudolig",
      "Zinon G. Labaya",
      "Fabian A. Aranaydo",
    ].map(formatCommitteePersonName),
  },
  {
    id: "com-29",
    name: "Committee on Transportation",
    chairman: formatCommitteePersonName("Felix M. Fudolig"),
    viceChairman: formatCommitteePersonName("Zinon G. Labaya"),
    members: [
      "Analyn H. Casane",
      "Albert G. Bompat",
      "Fabian A. Aranaydo",
    ].map(formatCommitteePersonName),
  },
];

export const mockCSOOrganizations: CSOOrganization[] = [
  {
    id: "cso-1",
    name: "Panglao Island Fisherfolk Association",
    officerName: "Roberto M. Salazar",
    position: "President",
    sbResolution: "Resolution No. 02-2026",
    founded: 2005,
  },
  {
    id: "cso-2",
    name: "Panglao Women's Development Council",
    officerName: "Maria Elena T. Cruz",
    position: "Chairperson",
    sbResolution: "Resolution No. 04-2026",
    founded: 2010,
  },
  {
    id: "cso-3",
    name: "Panglao Tourism Workers Alliance",
    officerName: "Eduardo B. Villamor",
    position: "President",
    sbResolution: "Resolution No. 06-2026",
    founded: 2012,
  },
  {
    id: "cso-4",
    name: "Dauis-Panglao Farmers Cooperative",
    officerName: "Juanito R. Paras",
    position: "Chairman",
    sbResolution: "Resolution No. 08-2026",
    founded: 2003,
  },
  {
    id: "cso-5",
    name: "Panglao Senior Citizens Federation",
    officerName: "Consolacion M. Duran",
    position: "President",
    sbResolution: "Resolution No. 10-2025",
    founded: 2008,
  },
  {
    id: "cso-6",
    name: "Panglao Youth Development Council",
    officerName: "Angela Joy S. Montero",
    position: "President",
    sbResolution: "Resolution No. 12-2025",
    founded: 2015,
  },
  {
    id: "cso-7",
    name: "Panglao Island Environmental Guardians",
    officerName: "Fernando A. Bohol",
    position: "Executive Director",
    sbResolution: "Resolution No. 14-2025",
    founded: 2011,
  },
  {
    id: "cso-8",
    name: "Panglao Persons with Disability Association",
    officerName: "Lilia G. Reyes",
    position: "President",
    sbResolution: "Resolution No. 16-2025",
    founded: 2013,
  },
  {
    id: "cso-9",
    name: "Panglao Transport Operators & Drivers Association",
    officerName: "Danilo C. Escuadro",
    position: "President",
    sbResolution: "Resolution No. 18-2025",
    founded: 2007,
  },
  {
    id: "cso-10",
    name: "Bolod Barangay Health Workers Association",
    officerName: "Rosemarie L. Tabilon",
    position: "President",
    sbResolution: "Resolution No. 20-2025",
    founded: 2009,
  },
  {
    id: "cso-11",
    name: "Panglao Vendors Livelihood Association",
    officerName: "Gloria D. Inoc",
    position: "Chairperson",
    sbResolution: "Resolution No. 22-2024",
    founded: 2016,
  },
  {
    id: "cso-12",
    name: "Panglao Dive Operators Association",
    officerName: "Mark Anthony P. Luna",
    position: "President",
    sbResolution: "Resolution No. 24-2024",
    founded: 2006,
  },
  {
    id: "cso-13",
    name: "Tawala Mothers Club",
    officerName: "Erlinda F. Mahinay",
    position: "President",
    sbResolution: "Resolution No. 26-2024",
    founded: 2014,
  },
  {
    id: "cso-14",
    name: "Panglao Island Heritage Preservation Society",
    officerName: "Atty. Noel V. Gallares",
    position: "Chairman",
    sbResolution: "Resolution No. 28-2024",
    founded: 2018,
  },
  {
    id: "cso-15",
    name: "Panglao Seaweed Growers Association",
    officerName: "Simplicio H. Dagatan",
    position: "President",
    sbResolution: "Resolution No. 30-2024",
    founded: 2004,
  },
];

export const mockCommitteeReports: CommitteeReport[] = [
  {
    id: "cr-1",
    reportNo: "CR 54",
    subject: "Regulation of Tourist Boat Operations in Panglao Waters",
    committee: "Committee on Tourism and Cultural Heritage",
    pdfUrl: SAMPLE_PDF_SNORKELING,
  },
  {
    id: "cr-2",
    reportNo: "CR 53",
    subject: "Proposed Amendments to the Municipal Revenue Code",
    committee: "Committee on Finance, Budget and Appropriations",
    pdfUrl: SAMPLE_PDF_TRICYCLE,
  },
  {
    id: "cr-3",
    reportNo: "CR 52",
    subject: "Establishment of a Coastal Resource Management Program",
    committee: "Committee on Environment",
    pdfUrl: SAMPLE_PDF_EUF,
  },
  {
    id: "cr-4",
    reportNo: "CR 51",
    subject: "Construction of Multi-Purpose Hall in Barangay Bolod",
    committee: "Committee on Public Works, Infrastructure & Public Utilities",
    pdfUrl: SAMPLE_PDF_SNORKELING,
  },
  {
    id: "cr-5",
    reportNo: "CR 50",
    subject: "Implementation of Anti-Drug Abuse Prevention Program",
    committee: "Committee on Peace & Order and Public Safety",
    pdfUrl: SAMPLE_PDF_TRICYCLE,
  },
  {
    id: "cr-6",
    reportNo: "CR 49",
    subject: "Scholarship Grant Program for Indigent Students of Panglao",
    committee: "Committee on Education",
    pdfUrl: SAMPLE_PDF_EUF,
  },
  {
    id: "cr-7",
    reportNo: "CR 48",
    subject: "Accreditation of Panglao Island Fisherfolk Association",
    committee: "Committee on Economic Development and Social Enterprise",
    pdfUrl: SAMPLE_PDF_SNORKELING,
  },
  {
    id: "cr-8",
    reportNo: "CR 47",
    subject: "Establishment of Municipal Health and Wellness Center",
    committee: "Committee on Health and Social Services",
    pdfUrl: SAMPLE_PDF_TRICYCLE,
  },
  {
    id: "cr-9",
    reportNo: "CR 46",
    subject: "Reclassification of Agricultural Land in Barangay Tawala",
    committee: "Committee on Human Settlement, Land Use & Development",
    pdfUrl: SAMPLE_PDF_EUF,
  },
  {
    id: "cr-10",
    reportNo: "CR 45",
    subject: "Allocation of Funds for Senior Citizen Medicine Assistance",
    committee: "Committee on Health and Social Services",
    pdfUrl: SAMPLE_PDF_SNORKELING,
  },
  {
    id: "cr-11",
    reportNo: "CR 44",
    subject: "Regulation of Tricycle Fare Rates within the Municipality",
    committee: "Committee on Economic Development and Social Enterprise",
    pdfUrl: SAMPLE_PDF_TRICYCLE,
  },
  {
    id: "cr-12",
    reportNo: "CR 43",
    subject: "Installation of Street Lights along Panglao Circumferential Road",
    committee: "Committee on Public Works, Infrastructure & Public Utilities",
    pdfUrl: SAMPLE_PDF_EUF,
  },
  {
    id: "cr-13",
    reportNo: "CR 42",
    subject: "Adoption of Solid Waste Management Plan for 2026-2030",
    committee: "Committee on Environment",
    pdfUrl: SAMPLE_PDF_SNORKELING,
  },
  {
    id: "cr-14",
    reportNo: "CR 41",
    subject: "Establishment of Municipal Disaster Risk Reduction Management Office",
    committee: "Committee on Peace & Order and Public Safety",
    pdfUrl: SAMPLE_PDF_TRICYCLE,
  },
  {
    id: "cr-15",
    reportNo: "CR 40",
    subject: "Annual Appropriations Ordinance Review for Fiscal Year 2026",
    committee: "Committee on Finance, Budget and Appropriations",
    pdfUrl: SAMPLE_PDF_EUF,
  },
];
