/** Default document categories copied to each new LGU (isolated per lgu_id). */
export const DEFAULT_DOCUMENT_CATEGORIES = [
  "Administrative Matters",
  "Agriculture",
  "Budget",
  "Celebrations",
  "Coastal Management",
  "Education",
  "Environment",
  "Fees and Charges",
  "Franchise",
  "Health",
  "History and Heritage",
  "Information Technology",
  "Infrastructure",
  "Land Use / Zoning",
  "Loans and other Fiscal Matters",
  "MOA/MOU/Usufruct/Contracts & Agreements",
  "Monetary Aide and other requests",
  "Municipal Lots",
  "NGO/PO Accreditation",
  "Peace and Order",
  "Penal, Criminal and Regulatory",
  "Purok System",
  "Risk Reduction",
  "Sisterhood Agreement",
  "Sports / Amusement",
  "Taxes",
  "Tourism",
  "Traffic Matters",
  "Transportation",
  "Waterworks",
  "Women and Children / PWD / Senior Citizen",
] as const;
